### ISSUE TITLE
Теги остались

### ISSUE THREAD

**Issue by KirillRum** [fox1va-the-fox/schems#2]
Удалил мод, теги остались. При попытке удалить игра крашится

**Comment by KirillRum** [comment]
и что мне делать

**Comment by KirillRum** [comment]
@fox1va-the-fox могу в ЛС краш репорт скинуть

**Comment by fox1va-the-fox** [comment]
> @fox1va-the-foxмогу в ЛС краш отчет скинуть

да, будет неплохо

**Comment by KirillRum** [comment]
> 

игру снести пришлось

**Comment by KirillRum** [comment]
пофиксил уже
