### ISSUE TITLE
В версии до 6 марта небыло схем? Или это у меня баг

### ISSUE THREAD

**Issue by Klololop** [fox1va-the-fox/schems#6]
![Screenshot_20230309_201003_com huawei filemanager](https://user-images.githubusercontent.com/106031370/224067317-fa3ebf0e-54d3-48fb-8a7c-11a545c18ad1.jpg)

**Comment by fox1va-the-fox** [comment]
дааа.... схемпак пересобирался и я никак не находил времени залить на гит, извиняюсь за неудобства

**Comment by fox1va-the-fox** [comment]
если быть точным то после 6 и до сегодняшнего дня

**Comment by fox1va-the-fox** [comment]
если нет вопросов можете закрывать
